//! `bashkit-coreutils-port` — port-time codegen for uutils/coreutils.
//!
//! Two modes, dispatched by the first positional arg:
//!
//! 1. **args mode** (legacy default — no subcommand):
//!
//!    ```text
//!    bashkit-coreutils-port <UUTILS_DIR> <UTIL> [<UUTILS_REV>]
//!    ```
//!
//!    Parses `<uutils>/src/uu/<util>/src/<util>.rs`, rewrites the
//!    `uu_app()` clap definition (resolves `translate!()`, drops
//!    Fluent-only chain steps, harvests `Arg::env(...)` annotations
//!    into a sidecar table for TM-INF-024's virtual-env shim), and
//!    prints a self-contained `<util>_args.rs` to stdout. See `args`
//!    module for details.
//!
//! 2. **module mode** (`port-module` subcommand):
//!
//!    ```text
//!    bashkit-coreutils-port port-module <UUTILS_DIR> <MODULE_NAME> [<UUTILS_REV>]
//!    ```
//!
//!    Vendors a platform-clean uucore module (e.g. `format`) verbatim
//!    into `crates/bashkit/src/builtins/generated/<out>/`. The set of
//!    vendored modules and their import-substitution policy lives in
//!    `crates/bashkit-coreutils-port/vendored.toml`. See `module` and
//!    `manifest` modules. Override the manifest path for testing via
//!    the `BASHKIT_VENDORED_TOML` env var.
//!
//! Both modes emit a shared banner shape (`// GENERATED by
//! bashkit-coreutils-port. DO NOT EDIT.` + uutils rev + regen
//! command + MIT attribution).
//!
//! Run manually when bumping the pinned uutils revision; output is
//! committed. See `knowledge/runtimes/coreutils-args-port.md`.

use std::path::PathBuf;
use std::process::ExitCode;

mod args;
mod ftl;
mod manifest;
mod module;

fn main() -> ExitCode {
    let argv: Vec<String> = std::env::args().collect();
    match argv.get(1).map(String::as_str) {
        Some("port-module") => run_port_module(&argv[2..]),
        Some("--help" | "-h") => {
            print_usage();
            ExitCode::SUCCESS
        }
        _ => run_port_args(&argv[1..]),
    }
}

fn print_usage() {
    eprintln!("bashkit-coreutils-port — port uutils/coreutils into bashkit");
    eprintln!();
    eprintln!("Usage:");
    eprintln!("  bashkit-coreutils-port <UUTILS_DIR> <UTIL> [<UUTILS_REV>]");
    eprintln!("      Args mode: regenerate <util>_args.rs to stdout.");
    eprintln!();
    eprintln!("  bashkit-coreutils-port port-module <UUTILS_DIR> <MODULE> [<UUTILS_REV>]");
    eprintln!("      Module mode: vendor a uucore module to disk.");
    eprintln!("      Module set + substitutions read from vendored.toml.");
}

fn run_port_args(rest: &[String]) -> ExitCode {
    let (uutils_dir, util, rev) = match rest {
        [dir, util] => (PathBuf::from(dir), util.clone(), "unknown".into()),
        [dir, util, rev] => (PathBuf::from(dir), util.clone(), rev.clone()),
        _ => {
            print_usage();
            return ExitCode::from(2);
        }
    };
    match args::run(&uutils_dir, &util, &rev) {
        Ok(out) => {
            print!("{out}");
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("error: {e:#}");
            ExitCode::FAILURE
        }
    }
}

fn run_port_module(rest: &[String]) -> ExitCode {
    let (uutils_dir, module_name, rev) = match rest {
        [dir, name] => (PathBuf::from(dir), name.clone(), "unknown".into()),
        [dir, name, rev] => (PathBuf::from(dir), name.clone(), rev.clone()),
        _ => {
            print_usage();
            return ExitCode::from(2);
        }
    };
    let manifest_path = std::env::var_os("BASHKIT_VENDORED_TOML")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("crates/bashkit-coreutils-port/vendored.toml"));
    let out_base = std::env::var_os("BASHKIT_GENERATED_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("crates/bashkit/src/builtins/generated"));
    match module::run(&uutils_dir, &module_name, &rev, &manifest_path, &out_base) {
        Ok(written) => {
            for path in &written {
                eprintln!("wrote {}", path.display());
            }
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("error: {e:#}");
            ExitCode::FAILURE
        }
    }
}
