<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Bashkit.Cli</RootNamespace>
    <AssemblyName>Bashkit.Cli</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Bashkit/Bashkit.csproj" />
  </ItemGroup>

</Project>
