import type { APIRoute } from "astro";
import {
  agentSteps,
  builtinCount,
  builtinPreview,
  defense,
  evalSnapshot,
  evals,
  heroQuickLinks,
  heroStats,
  homeHero,
  homeNavigation,
  languages,
  resources,
  signals,
  skillRepoUrl,
  surfaces,
} from "../content/home";
import { DOC_META } from "./docs/_meta";

export const prerender = true;

export const GET: APIRoute = () => {
  const markdown = [
    "---",
    'title: "Bashkit"',
    `description: ${JSON.stringify(homeHero.description)}`,
    "---",
    "",
    "# Bashkit",
    "",
    homeHero.description,
    "",
    "## Navigation",
    "",
    ...homeNavigation.map((item) => `- [${item.label}](${item.href}) - ${item.detail}`),
    "- [llms.txt](/llms.txt) - Curated, machine-readable index of this site for coding agents.",
    "- [llms-full.txt](/llms-full.txt) - Every guide inlined into one document.",
    "",
    "## Quick starts",
    "",
    ...languages.flatMap((lang) => [
      `### ${lang.eyebrow}`,
      "",
      lang.title,
      "",
      "```sh",
      lang.install,
      "```",
      "",
    ]),
    "## Agent skill",
    "",
    "Install the Bashkit skill before asking a coding agent to wire Bashkit into a host project.",
    "",
    ...agentSteps.flatMap((step, index) => [
      `${index + 1}. ${step.title}: ${step.detail}`,
      ...(step.command ? ["", "```sh", step.command, "```"] : []),
      "",
    ]),
    `- [View skill contents](${skillRepoUrl}) - the SKILL.md and reference files the skill installs.`,
    "",
    "## Product surface",
    "",
    ...surfaces.map((item) => `- **${item.title}** - ${item.detail}`),
    "",
    "## Runtime proof",
    "",
    ...signals.map((item) => `- **${item.title}** - ${item.detail}`),
    "",
    "## Builtins",
    "",
    `Preview: ${builtinPreview.map((name) => `\`${name}\``).join(", ")}.`,
    "",
    `- [See all ${builtinCount} builtins](/builtins)`,
    "",
    "## Security",
    "",
    ...defense.map((item) => `- **${item.title}** - ${item.detail}`),
    "",
    "## Evals",
    "",
    `Results below are from the [${evalSnapshot.date}](${evalSnapshot.href}) eval run.`,
    "",
    "| Model | Score | Tasks passed |",
    "|---|---:|---:|",
    ...evals.map((row) => `| ${row.model} | ${row.score} | ${row.passed} |`),
    "",
    "## Docs",
    "",
    ...DOC_META.map((doc) => `- [${doc.title}](/docs/${doc.slug}/) - ${doc.summary}`),
    "",
    "## Resources",
    "",
    ...heroStats.map((stat) => `- [${stat.label}: ${stat.value}](${stat.href})`),
    ...heroQuickLinks.map((link) => `- [${link.title}](${link.href}) - ${link.detail}`),
    ...resources.map((item) => `- [${item.title}](${item.href}) - ${item.detail}`),
    "",
  ].join("\n");

  return new Response(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
    },
  });
};
