<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Monty.Cli</RootNamespace>
    <AssemblyName>Monty.Cli</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Monty/Monty.csproj" />
  </ItemGroup>

</Project>
