# Based on python/typeshed's `stdlib/unicodedata.pyi`, stripped down to the
# functions and constants Monty actually implements at runtime.

from typing import Final, Literal, TypeVar, overload

_T = TypeVar('_T')

_NormalizationForm = Literal['NFC', 'NFD', 'NFKC', 'NFKD']

unidata_version: Final[str]

def category(chr: str, /) -> str: ...
def combining(chr: str, /) -> int: ...
def is_normalized(form: _NormalizationForm, unistr: str, /) -> bool: ...
def lookup(name: str, /) -> str: ...
@overload
def name(chr: str, /) -> str: ...
@overload
def name(chr: str, default: _T, /) -> str | _T: ...
def normalize(form: _NormalizationForm, unistr: str, /) -> str: ...
